In [4]:
import numpy as np

In [3]:
# creation
a=np.array([1,2,3])
a

array([1, 2, 3])

In [4]:
a.shape

(3,)

In [11]:
# why to use : Multi-dimentional data ( n-dimentional arrays )

In [5]:
b=np.array([[1,2],[3,4],[4,5]])
b

array([[1, 2],
       [3, 4],
       [4, 5]])

In [13]:
b.shape

(3, 2)

In [16]:
b.reshape((2,3))

array([[1, 2, 3],
       [4, 4, 5]])

In [18]:
b.reshape((6))

array([1, 2, 3, 4, 4, 5])

In [19]:
c=np.zeros((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
c=np.ones((2,3))
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
# Get a range of values - arrange(initial,last+1,step_count)
odd=np.arange(1,10,2)
even=np.arange(2,10,2)
print(f'Even : {even} \nOdd : {odd}')

Even : [2 4 6 8] 
Odd : [1 3 5 7 9]


In [32]:
# range of values with linspace - linspace(initial,last,how_many_nums_you_want_in_between_the_two)
lin_sp=np.linspace(1,10,10)
print(f'Linspace : {lin_sp}')

Linspace : [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [6]:
b

array([[1, 2],
       [3, 4],
       [4, 5]])

In [38]:
b[:]

array([[1, 2],
       [3, 4],
       [4, 5]])

In [39]:
b[:0]

array([], shape=(0, 2), dtype=int32)

[ rows , columns ]

In [40]:
b[:,0]

array([1, 3, 4])

In [43]:
b[0,0]

1

In [7]:
b*2

array([[ 2,  4],
       [ 6,  8],
       [ 8, 10]])

In [8]:
for i in range(3):
    for j in range(2):
        b[i,j]=b[i,j]*2
b

array([[ 2,  4],
       [ 6,  8],
       [ 8, 10]])

In [11]:
b>7

array([[False, False],
       [False,  True],
       [ True,  True]])

In [17]:
print(np.mean(b))
# for columns 
print(np.mean(b,axis=0))
# for rows
print(np.mean(b,axis=1))

6.333333333333333
[5.33333333 7.33333333]
[3. 7. 9.]


In [18]:
# stack em
np.concatenate([b,b*2],axis=1)

array([[ 2,  4,  4,  8],
       [ 6,  8, 12, 16],
       [ 8, 10, 16, 20]])

In [1]:
from tensorflow.keras.datasets import mnist

In [2]:
(X_train,y_train),(X_test,y_test)=mnist.load_data()

11490434/11490434 [==============================] - 2s 0us/step


In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
import pandas as pd

In [7]:
df=pd.read_csv('Data/housing.csv')
df

longitude  latitude  ...  median_house_value  ocean_proximity
0        -122.23     37.88  ...            452600.0         NEAR BAY
1        -122.22     37.86  ...            358500.0         NEAR BAY
2        -122.24     37.85  ...            352100.0         NEAR BAY
3        -122.25     37.85  ...            341300.0         NEAR BAY
4        -122.25     37.85  ...            342200.0         NEAR BAY
...          ...       ...  ...                 ...              ...
20635    -121.09     39.48  ...             78100.0           INLAND
20636    -121.21     39.49  ...             77100.0           INLAND
20637    -121.22     39.43  ...             92300.0           INLAND
20638    -121.32     39.43  ...             84700.0           INLAND
20639    -121.24     39.37  ...             89400.0           INLAND

[20640 rows x 10 columns]

In [8]:
df.to_numpy()

array([[-122.23, 37.88, 41.0, ..., 8.3252, 452600.0, 'NEAR BAY'],
       [-122.22, 37.86, 21.0, ..., 8.3014, 358500.0, 'NEAR BAY'],
       [-122.24, 37.85, 52.0, ..., 7.2574, 352100.0, 'NEAR BAY'],
       ...,
       [-121.22, 39.43, 17.0, ..., 1.7, 92300.0, 'INLAND'],
       [-121.32, 39.43, 18.0, ..., 1.8672, 84700.0, 'INLAND'],
       [-121.24, 39.37, 16.0, ..., 2.3886, 89400.0, 'INLAND']],
      dtype=object)